### PR TITLE
Add model for Flickr30k Entities in the paper

### PR DESCRIPTION
**Pull request by jaesuny**
Training a model for Flickr30k may take 120 seconds per epoch using 4 Titan XPs.

### CODE REVIEW

**Comment by jnhwkim** [comment]
Out of just curiosity, 1 Titan Xp might be faster than 4 due to the cost for distributed computing?

**Comment by jaesuny** [comment]
Interesting. I'll check it out.

**Comment by jaesuny** [comment]
> Out of just curiosity, 1 Titan XP might be faster than 4 due to the cost for distributed computing?

Using single TITAN Xp, it takes 180 seconds per epoch when batch size is 256. 
It seems that [clipping gradient](https://github.com/jnhwkim/ban-vqa/pull/13/files#diff-2f5453e3af9cdf5423c5e3919017e8c8R82) is a bottleneck on single XP accounting for 38% of training time while 17% on 4 XPs.
Clipping gradient is slower 3 times on single GPU than 4 GPUs whereas other operations did not show such difference.

**Comment by jnhwkim** [comment]
I'll merge this PR in shortly.

**Pull request merged**
